# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions

# Set up virtualenvwrapper
export WORKON_HOME=$HOME/.virtualenvs
export PIP_VIRTUALENV_BASE=$WORKON_HOME
export VIRTUALENV_USE_DISTRIBUTE=true
export PIP_RESPECT_VIRTUALENV=true
source /usr/bin/virtualenvwrapper.sh

alias phttp="http --verify no --cert ~/.pulp/user-cert.pem"

REPOS=("pulp" "pulp_deb" "pulp_docker" "pulp_openstack" "pulp_ostree" "pulp_puppet" "pulp_python" "pulp_rpm")
SERVICES=("goferd" "httpd" "pulp_workers" "pulp_celerybeat" "pulp_resource_manager" "pulp_streamer")

pstart() {
    _paction start
}

pstop() {
    _paction stop
}

prestart() {
    _paction restart
}

pstatus() {
    _paction status
}

preset() {
    echo "Due to its similarity to 'prestart', 'preset' has been renamed to 'pclean'."
    echo "Please use 'pclean' instead, and remember to update any script that might be calling it."
    sleep 3
    pclean
}

pclean() {
    pstop;

    pushd ~/devel/
    # Remove and unlink all development files in reverse order (uninstall pulp last)
    for (( idx=${#REPOS[@]} ; idx>0 ; idx-- )) ; do
        repo="${REPOS[idx-1]}"
        if [ -d $repo ]; then
            pushd $repo
            sudo ./pulp-dev.py -U
            popd
        fi
    done

    # Destroy mongo DB and clean up pulp-related files
    mongo pulp_database ~/drop_database.js;
    sudo rm -rf /var/lib/pulp/*;
    find ~/devel/pulp* -name '*.py[co]' -delete;
    rm -f ~/.pulp/user-cert.pem

    # Re-install and relink development files
    for repo in ${REPOS[@]}; do
        if [ -d $repo ]; then
            pushd $repo
            sudo ./pulp-dev.py -I
            popd
        fi
    done
    popd

    sudo -u apache pulp-manage-db;
    setup_crane_links;
    pstart;
    ppopulate;
}

pjournal() {
    # build up the journalctl cmdline per-unit
    journal_cmd="journalctl"
    for svc in ${SERVICES[@]}; do
        journal_cmd="$journal_cmd -u $svc"
    done

    if [ -z $1 ]; then
        # not passed any args, follow the units' journals by default
        $journal_cmd -f
    else
        # passed some args, send all args through to journalctl
        $journal_cmd $@
    fi
}

ptests() {
    pushd $HOME/devel;
    for repo in ${REPOS[@]}; do
        if [ -d $repo ]; then
            pushd $repo;
            workon $repo;
            ./run-tests.py -x --enable-coverage;
            deactivate;
            popd;
        fi
    done;
    popd;
}

_paction() {
    sudo systemctl $1 ${SERVICES[@]}
}

psmash() {
    # We start and end with {push,pop}d because workon changes CWD and we don't want to user's CWD
    # to be altered when they type pulp-smash.
    pushd ~;
    workon pulp-smash;
    prestart;
    if make lint test
    then
        python -m unittest2 discover ~/devel/pulp-smash/pulp_smash;
    fi
    deactivate;
    popd;
}

ppopulate() {
    if [ ! -f $HOME/.pulp/user-cert.pem ]; then
        pulp-admin login -u admin -p admin
    fi

    if [ -d $HOME/devel/pulp_docker ]; then
        pulp-admin docker repo create --repo-id busybox --feed https://index.docker.io \
            --upstream-name busybox
    fi

    if [ -d $HOME/devel/pulp_rpm ]; then
        pulp-admin rpm repo create --repo-id=zoo \
            --feed=https://repos.fedorapeople.org/repos/pulp/pulp/demo_repos/zoo/
    fi

    if [ -d $HOME/devel/pulp_puppet ]; then
        pulp-admin puppet repo create --repo-id=forge \
            --feed=http://forge.puppetlabs.com \
            --queries=torssh
    fi

    if [ -d $HOME/devel/pulp_python ]; then
        pulp-admin python repo create --repo-id=pypi \
            --feed=https://pypi.python.org/ \
            --package-names=pip
    fi
}

pprocs() {
    print_procs() {
        # prints a header string with number of pids, list of pids, and a newline spacer
        # $1 is the header string, $2 is a newline-separated list of pids, see usage below
        echo "$1 ($(echo $2|wc -w)):"
        echo $2
        echo
    }

    # override IFS to prevent bash splitting pgrep output on newlines
    IFS=''
    print_procs "Pulp worker processes" `pgrep -f "pulp.server.async.app -c 1"`
    print_procs "Pulp Resource Manager processes" `pgrep -f "pulp.server.async.app -n resource_manager"`
    print_procs "Pulp Celerybeat processes:" `pgrep -f "pulp.server.async.celery_instance.celery"`
    print_procs "Pulp WSGI processes:" `pgrep -f "wsgi:pulp"`
    unset IFS
}

pdebug() {
    telnet 127.0.0.1 4444
}

setup_crane_links() {
    # If Crane is present, let's set up the publishing symlinks so that the app files can be used
    if [ -d $HOME/devel/crane ]; then
        pushd $HOME/devel/crane
        mkdir -p metadata/v1 metadata/v2
        setfacl -m u:apache:rwx metadata/*
        sudo -u apache mkdir -p /var/lib/pulp/published/docker/v1 /var/lib/pulp/published/docker/v2
        sudo -u apache ln -s $HOME/devel/crane/metadata/v1 /var/lib/pulp/published/docker/v1/app
        sudo -u apache ln -s $HOME/devel/crane/metadata/v2 /var/lib/pulp/published/docker/v2/app
        popd
    fi
}

export DJANGO_SETTINGS_MODULE=pulp.server.webservices.settings
export CRANE_CONFIG_PATH=$HOME/devel/crane/crane.conf
