"""
Contains constants used for generic state processing & reporting for tasks
"""

PROGRESS_STEP_ID_KEY = u'step_id'
PROGRESS_ITEMS_TOTAL_KEY = u'items_total'
PROGRESS_NUM_PROCESSED_KEY = u'num_processed'
PROGRESS_NUM_SUCCESSES_KEY = u'num_success'
PROGRESS_NUM_FAILURES_KEY = u'num_failures'
PROGRESS_DESCRIPTION_KEY = u'description'
PROGRESS_STATE_KEY = u'state'
PROGRESS_ERROR_DETAILS_KEY = u'error_details'

STATE_NOT_STARTED = u'NOT_STARTED'
STATE_RUNNING = u'IN_PROGRESS'
STATE_COMPLETE = u'FINISHED'
STATE_FAILED = u'FAILED'
STATE_SKIPPED = u'SKIPPED'
STATE_CANCELLED = u'CANCELLED'

FINAL_STATES = (STATE_COMPLETE, STATE_FAILED, STATE_SKIPPED)
