"""
Contains constants used for generic state processing & reporting for tasks
"""

PROGRESS_TOTAL_KEY = 'total'
PROGRESS_PROCESSED_KEY = 'processed'
PROGRESS_SUCCESSES_KEY = 'successes'
PROGRESS_FAILURES_KEY = 'failures'

PROGRESS_STATE_KEY = 'state'
PROGRESS_NUM_SUCCESS_KEY = 'num_success'
PROGRESS_NUM_ERROR_KEY = 'num_error'
PROGRESS_ITEMS_LEFT_KEY = 'items_left'
PROGRESS_ITEMS_TOTAL_KEY = 'items_total'
PROGRESS_ERROR_DETAILS_KEY = 'error_details'

STATE_NOT_STARTED = 'NOT_STARTED'
STATE_RUNNING = 'IN_PROGRESS'
STATE_COMPLETE = 'FINISHED'
STATE_FAILED = 'FAILED'
STATE_SKIPPED = 'SKIPPED'
STATE_CANCELLED = 'CANCELLED'

FINAL_STATES = (STATE_COMPLETE, STATE_FAILED, STATE_SKIPPED)
