#!/bin/bash
#
# pulp-cds         Startup script for the Pulp CDS services
#
# chkconfig: - 97 9
#
### BEGIN INIT INFO
# Required-Start: $goferd $httpd
# Required-Stop: $httpd $goferd
# Short-Description: start and stop the Pulp CDS webservices
# Description: Pulp is comprehensive content repository and consumer management

export SYSTEMCTL_SKIP_REDIRECT=1
export SYSTEMCTL_IGNORE_DEPENDENCIES=1

. /etc/rc.d/init.d/functions

RETVAL=0
SERVICE=/sbin/service


start() {
    $SERVICE goferd start || RETVAL=$?
    [ $RETVAL = 0 ] && $SERVICE httpd start || RETVAL=$?
    return $RETVAL
}

stop() {
    $SERVICE httpd stop
    $SERVICE goferd stop
    return $RETVAL
}

status() {
    $SERVICE httpd status || RETVAL=$?
    [ $RETVAL = 0 ] && $SERVICE goferd status || RETVAL=$?
    [ $RETVAL = 0 ]
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    status)
        status
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo $"Usage: pulp-cds {start|stop|restart|status}"
        RETVAL=3
esac

exit $RETVAL
