#!/bin/sh -e
# ================================================================
#  pulp_resource_manager - Start the Pulp resource manager daemon.
# ================================================================
#
# :Usage: /etc/init.d/pulp_resource_manager {start|stop|force-reload|restart|try-restart|status}
# :Configuration file: /etc/default/pulp_resource_manager
#
# See http://docs.celeryproject.org/en/latest/tutorials/daemonizing.html#generic-init-scripts


### BEGIN INIT INFO
# Provides:          pulp_resource_manager
# Required-Start:    $network $local_fs $remote_fs
# Required-Stop:     $network $local_fs $remote_fs
# Should-Start:      mongod qpidd rabbitmq-server
# Default-Start:     3 4 5
# Default-Stop:      0 1 2 6
# Short-Description: pulp's resource manager daemon
### END INIT INFO

. /etc/rc.d/init.d/pulp_workers
