#!/usr/bin/python
"""
Pulp Command Line Launch Script

Copyright 2008, Red Hat, Inc
Devan Goodwin <dgoodwin@redhat.com>

This software may be freely redistributed under the terms of the GNU
general public license.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
"""

import sys

from pulp.cli.cli import PulpCommandLine
PulpCommandLine().main(sys.argv)

