#!/bin/bash
# TODO:
#    0) add comments to this script
#    1) Implement checking for: "The following options were specified but do not exist on the command:".
#       So far, tab completion will work if not necessary option is specified
#       It can be done by smth like
#
#       if [[ $($COMP_LINE | egrep -o "^The following options were specified") != "" ]]; then
#               :
#
#       but it works very slow then
#
#    2) It works if a wrong option was specified:
#       >>pulp-admin rpm repo wrong-section [TAB][TAB]
#       content  copy     create   delete   export   group    --help   list     publish  remove   search   sync     update   uploads
#       Easily fixed after bug 1132539 fix


_elogin_pa_options()
{
        #returns tab completion for the options of the first level if needed

        pa_log_opt=$(comm -13 <(for word in ${1}; do echo $word; done | sort) <(for word in $2; do echo $word; done | sort))

        if [[ $1 == *\ -u* ]] || [[ $1 == *--username* ]]; then
                pa_log_opt=$(echo $pa_log_opt | sed "s/\(-u\|--username\)//g")
        fi

        if [[ $1 == *\ -p* ]] || [[ $1 == *--password* ]]; then
                pa_log_opt=$(echo $pa_log_opt | sed "s/\(-p\|--password\)//g")
        fi
        echo $pa_log_opt
}


_epulp-admin_tab()
{
  local pa_cur pa_options pa_sections grep_pa_sections

  COMPREPLY=()
  pa_cur=${COMP_WORDS[COMP_CWORD]}
  pa_options="-u -p --username --password --help -h --debug --config"
  pa_sections="tasks auth bindings event orphan consumer puppet rpm iso repo server"
  grep_pa_sections=$(echo $COMP_LINE | egrep -o "(tasks|auth|bindings|event|orphan|consumer|puppet|rpm|iso|repo|server)(?|.)*" )

  if [[ $COMP_LINE == *logout?* ]] || [[ $COMP_LINE == *--map?* ]] || [[ $COMP_LINE == *\ -h?* ]] || [[ $COMP_LINE == *--help?* ]]; then
        :

  elif [[ $COMP_LINE == *login?* ]]; then

        login_pa_options=$(_elogin_pa_options "$COMP_LINE" "$pa_options")
        COMPREPLY=( $( compgen -W "$login_pa_options" -- "$pa_cur" ) )

  elif [ $COMP_CWORD -eq 1 ]; then
        if [[ "$pa_cur" == -* ]]; then
                COMPREPLY=( $( compgen -W "$pa_options --map" -- "$pa_cur" ) )
        else
                COMPREPLY=( $( compgen -W "$pa_options $pa_sections login logout --map" -- "$pa_cur" ) )
        fi

  elif [[ $grep_pa_sections != "" ]]; then
        COMPREPLY=( $( compgen -W "$(pulp-admin $grep_pa_sections --help | egrep -o '^  [A-Za-z_|-]+ | \-\-[A-Za-z_|-]+' | tr -d ' ' | sort | uniq ) --help" -- "$pa_cur" ) )

  else
        nologin_pa_options=$(_elogin_pa_options "$COMP_LINE" "$pa_options")
        COMPREPLY=( $( compgen -W "$nologin_pa_options $pa_sections" -- "$pa_cur" ) )

  fi
} &&

complete -F _epulp-admin_tab pulp-admin
