---
- name: Install packages
  dnf: name={{ item }} state=present
  with_items:
    - qpid-cpp-client
    - qpid-cpp-server
    - qpid-cpp-server-linearstore
    - qpid-tools

- name: Start and enable services
  service: name=qpidd state=started enabled=yes
