#!/bin/bash
#
# pulp-server         Startup script for the Pulp Web Services
#
# chkconfig: - 97 9
#
### BEGIN INIT INFO
# Required-Start: $mongod $qpidd $httpd
# Required-Stop: $httpd $qpidd $mongod
# Short-Description: start and stop the Pulp webservices
# Description: Pulp is comprehensive content repository and consumer management 
### END INIT INFO

export SYSTEMCTL_SKIP_REDIRECT=1
export SYSTEMCTL_IGNORE_DEPENDENCIES=1

. /etc/rc.d/init.d/functions

RETVAL=0
SERVICE=/sbin/service
init_file=/var/lib/pulp/init.flag

init() {
    MONGODIR=/var/lib/mongodb
    if [ ! -d $MONGODIR ]; then
        mkdir -p $MONGODIR
        chmod 755 $MONGODIR
        chown mongodb:root $MONGODIR
    fi
    $SERVICE mongod start
    /usr/bin/pulp-migrate
    RETVAL=$?
    [ $RETVAL = 0 ] && touch ${init_file}
    return $RETVAL
}

start() {
    if [ ! -f $init_file ]; then
        echo $"Pulp database not initialized, please run: $0 init"
        RETVAL=2
        return $RETVAL
    fi
    $SERVICE mongod start || RETVAL=$?
    [ $RETVAL = 0 ] && $SERVICE qpidd start || RETVAL=$?
    [ $RETVAL = 0 ] && $SERVICE httpd start || RETVAL=$?
    return $RETVAL
}

stop() {
    $SERVICE httpd stop
    $SERVICE qpidd stop
    $SERVICE mongod stop
    return $RETVAL
}

status() {
    $SERVICE mongod status || RETVAL=$?
    [ $RETVAL = 0 ] && $SERVICE httpd status || RETVAL=$?
    [ $RETVAL = 0 ] && $SERVICE qpidd status || RETVAL=$?
    return $RETVAL
}

case "$1" in
    init)
        init
        ;;
    start)
        start
        ;;
    status)
        status
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo $"Usage: pulp-server {init|start|stop|status|restart}"
        RETVAL=3
esac

exit $RETVAL
