# Generated by Django 2.1.7 on 2019-02-25 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pulp_app', '0002_task_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryVersionContentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_type', models.CharField(choices=[('A', 'added'), ('P', 'present'), ('R', 'removed')], max_length=1)),
                ('content_type', models.TextField()),
                ('count', models.IntegerField()),
                ('repository_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counts', to='pulp_app.RepositoryVersion')),
            ],
        ),
    ]
