name    'jcline-pulp'
version '0.1.10'
source 'https://github.com/pulp/pulp/tree/master/playpen/puppet'
author 'Jeremy Cline'
license 'GPL, Version 2.0'
summary 'This module can be used to install and configure Pulp servers and consumers.'
description 'UNKNOWN'
project_page 'UNKNOWN'

## Add dependencies, if any:
dependency 'puppetlabs/stdlib', '>=3.2.0'
